### ISSUE TITLE
No slave.h included in package

### ISSUE THREAD

**Issue by DeshmukhAkshay** [jonathan-daniel/CPyModbus#2]
As no slave.h is included in package which is used in CPyModbus/core/slave.c, while installing CPyModbus in raspberry pi it gives below error
cpymodbus/core/slave.c:9:19: fatal error : slave.h: No such file or directory
#include "slave.h"

**Comment by jonathan-daniel** [comment]
I will look into it

**Comment by jonathan-daniel** [comment]
Can you try the master branch?

@DeshmukhAkshay 66ba50fca19bd6c07a0ea17be06ad3275d4c2c29

**Comment by DeshmukhAkshay** [comment]
@jonathan-daniel it works well with your edited code and new directions to use CPyModbus are simplified.
Thanks for your help.

**Comment by jonathan-daniel** [comment]
No problem
